---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    provider: fabric8
    project: alpasino
    version: 1.0-SNAPSHOT
    group: movies
  name: alpasino
spec:
  ports:
  - name: jolokia
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    project: alpasino
    provider: fabric8
    group: movies
