---
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=alpasino&var-version=1.0-SNAPSHOT
  labels:
    provider: fabric8
    project: alpasino
    version: 1.0-SNAPSHOT
    group: movies
  name: alpasino
spec:
  replicas: 1
  selector:
    project: alpasino
    provider: fabric8
    group: movies
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=alpasino&var-version=1.0-SNAPSHOT
      labels:
        provider: fabric8
        project: alpasino
        version: 1.0-SNAPSHOT
        group: movies
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: movies/alpasino:snapshot-210503-201223-0515
        imagePullPolicy: IfNotPresent
        name: java-exec
        ports:
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
